# Site settings
title: Cool story, bro
email: aleksartamonov@gmail.com
description: "Blog with cool stories."
baseurl: ""
url: "http://vk.com/mlexus"
username: aleksartamonov
twittername: notastronom
paginate: 5
# Build settings
markdown: kramdown
permalink: pretty
